language: ruby
rvm:
  - "2.3.1"
env:
  - DB=sqlite
script:
  - bundle exec rake db:create db:schema:load RAILS_ENV=test
  - bundle exec rake db:test:prepare
  - bundle exec rake test test/
  - bundle exec rspec --format doc spec/
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - export SECRET_KEY_BASE=$(bundle exec rake secret)
  - export SECRET_TOKEN=$(bundle exec rake secret)
